# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 1.20.6-neoforge ]
  pull_request:
    branches: [ 1.20.6-neoforge ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          gradle-home-cache-cleanup: true
          add-job-summary: 'on-failure'
      - run: ./gradlew build
      - run: ./gradlew runData
